### ISSUE TITLE
App keeps crashing 

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#65]
I'm trying to have the map marker load up from firebase but the App keeps crashing while trying to load and no Error! #15 
![screen shot 2017-03-28 at 7 40 03 pm](https://cloud.githubusercontent.com/assets/15060826/24433572/471fdb2c-13ef-11e7-8658-062c4db69e50.png)
![screen shot 2017-03-28 at 7 39 16 pm](https://cloud.githubusercontent.com/assets/15060826/24433573/473db462-13ef-11e7-8a6e-6d804a9ea375.png)

**Comment by Andimoh** [comment]
@jake32321

**Comment by jake32321** [comment]
Ah.  for the reference you need to make sure that it goes to the right child.  I.E. to get the reference for that you need to make the reference to be something like database().getReference.child('lots')... but to the level where you can get the child lattitude and longitude.  Right now you are referencing the root node of the database. The issue can be seen at the top of the output with the null ref since lattitude is nonexistent on that node.

**Comment by jake32321** [comment]
also, the input will be a string that needs to be converted to a double.

**Comment by jake32321** [comment]
@Andimoh

**Comment by Andimoh** [comment]
OK Thanks!
