### ISSUE TITLE
click on marker to show all spots

### ISSUE THREAD

**Issue by Andimoh** [SIU-CS/Finite_Loop-production#72]
can you explain how to show all the spots please? i tried using the onMarkerClick doesn't work #8 

@jake32321

**Comment by jake32321** [comment]
@Andimoh Here's a good place to look: [http://stackoverflow.com/questions/39650262/using-firebase-to-populate-my-listview](url) as well as here: [http://stackoverflow.com/questions/27414344/how-to-populate-android-listview-with-information-from-firebase-query](url)

**Comment by Andimoh** [comment]
![screen shot 2017-04-02 at 7 05 31 pm](https://cloud.githubusercontent.com/assets/15060826/24592169/891fbb00-17d7-11e7-9592-162d48c5059c.png)


don't i need some kind of onClickMarker method ? to know if markers been clicked to populate the list view ?
at this point i'm not even sure i understand what i'm doing?? 
@jake32321

**Comment by jake32321** [comment]
Yes there is a onMarkerClick method that would work great for this.  Also, check to make sure that you are iterating through all the lots too.  We only need their spots on a click of a marker so that would go inside the onMarker click method.  You would get that specific lot and then populate the list before initiating the next intent which would be that list view.  Here's a good reference for using that on marker click: [http://stackoverflow.com/questions/14226453/google-maps-api-v2-how-to-make-markers-clickable](url). However though, that would initiate on clicking any of the said markers.  Catch my drift? @Andimoh

**Comment by jake32321** [comment]
Also, don't be afraid to read the docs or SO.  There are many people that have a similar or identical issue.  I can always try and help you tomorrow if I have time.  If not it shouldn't be super hard to finish next sprint since Sprint 3 is light for us.

**Comment by jake32321** [comment]
This issue should be marked for Sprint 3. Marking it now. @Andimoh @agnarvaez @Maha1990
